INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (318, 0, 'cubiculo1', 4);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (319, 0, 'cubiculo2', 4);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (320, 0, 'cubiculoVideo1', 5);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (321, 0, 'cubiculoVideo2', 5);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (322, 1, 'canchaFutbolTenis1', 9);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (323, 1, 'canchaFutbolTenis2', 9);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (324, 1, 'canchaTenis', 7);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (325, 1, 'canchaMultiple', 8);
INSERT INTO public.espacios (id, cupos, nombre, tipo_espacio_id) VALUES (326, 15, 'cupoGimnasio', 6);